version: '3.4'

### places where the most important data is
volumes:
  etc_slurm:
  slurm_jobdir:
  var_log_slurm:
  var_lib_mysql:
  insaflu-website:
  insaflu-software:
  conda envs:
  binaries:

  etc_munge:
    driver: local-persist
    driver_opts:
      mountpoint: ${BASE_PATH_DATA}/munge
  pg_data:
    driver: local-persist
    driver_opts:
      mountpoint: ${BASE_PATH_DATA}/postgres/postgres_data
  insaflu-ubuntu-data:
    driver: local-persist
    driver_opts:
      mountpoint: ${BASE_PATH_DATA}/insaflu/data/all_data
  insaflu-ubuntu-predefined_dbs:
    driver: local-persist
    driver_opts:
      mountpoint: ${BASE_PATH_DATA}/insaflu/data/predefined_dbs
  insaflu-ubuntu-env:
    driver: local-persist
    driver_opts:
      mountpoint: ${BASE_PATH_DATA}/insaflu/env
  insaflu-ubuntu-log-insaflu:
    driver: local-persist
    driver_opts:
      mountpoint: ${BASE_PATH_DATA}/insaflu/log/insaFlu
  insaflu-ubuntu-log-httpd:
    driver: local-persist
    driver_opts:
      mountpoint: ${BASE_PATH_DATA}/insaflu/log/httpd
  televir:
    driver: local-persist
    driver_opts:
      mountpoint: ${BASE_PATH_DATA}/televir/

### this is necessary to set an ip to SGE in insaflu
networks:
  insaflu_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.1.0.0/24

  slurm-network:
    driver: bridge

services:
  # DB for Insaflu
  # test database - psql -U flu_user -W -h localhost -d insaflu_db
  db_insaflu:
    build: components/postgres_postgis/.
    restart: always
    container_name: postgres
    hostname: db_insaflu
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "flu_user"
      POSTGRES_PASSWORD: "flu_user_pass"
      POSTGRES_DB: "insaflu_db"
      PGDATA: /var/lib/postgresql/data/pgdata
    expose:
      - 5432
    networks:
      insaflu_net:
        ipv4_address: 10.1.0.2

  # responsible to m
  officer:
    image: funkyfuture/deck-chores:1
    restart: unless-stopped
    environment:
      TIMEZONE: "${TIMEZONE}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      
  # TELEVIR
  televir-server:
    build: components/televir/.
    container_name: televir-server
    image: ${USERNAME_IMAGE}:${TELEVIR_IMAGE}
    hostname: televir
    restart: on-failure
    volumes:
      - televir:/televir/mngs_benchmark
    depends_on:
      - officer
    environment:
      - SGE_ROOT=/opt/sge
    tty: true
    stdin_open: true
    networks:
      insaflu_net:
        ipv4_address: 10.1.0.5
    command: [ "move" ]
  
  # insaflu
  # password and database login are defined in components/insaflu/configs/insaflu.env 
  insaflu-ubuntu:
    build: 
      context: components/insaflu-ubuntu/.
      args:
        SLURM_TAG: ${SLURM_TAG}
    container_name: insaflu-ubuntu
    image: ${USERNAME_IMAGE}:${IMAGE}
    hostname: insaflu
    restart: "on-failure"
    volumes:
      - televir:/televir/mngs_benchmark
      - insaflu-ubuntu-data:/insaflu_web/INSaFLU/media
      - insaflu-ubuntu-predefined_dbs:/insaflu_web/INSaFLU/static_all/db
      - insaflu-ubuntu-env:/insaflu_web/INSaFLU/env
      - insaflu-ubuntu-log-insaflu:/var/log/insaFlu
      - insaflu-ubuntu-log-httpd:/var/log/httpd
      - insaflu-website:/insaflu_web/INSaFLU
      - insaflu-software:/software
      - slurm_jobdir:/data
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm

    labels:
      deck-chores.update-pangolin.command: sh -c "/software/update_pangolin.sh"
      # weekly, daily, hourly, every minute and every second.
      deck-chores.update-pangolin.interval: hourly
    depends_on:
      - db_insaflu
      - officer
      - slurmctld
      - c1
      - c2
    environment:
      - SGE_ROOT=/opt/sge
    ports:
      - "${APP_PORT}:80"
    tty: true
    stdin_open: true
    networks:
      insaflu_net:
        ipv4_address: 10.1.0.4
      slurm-network:
    command: [ "init_all" ]

  mysql:
    image: mariadb:10.11
    hostname: mysql
    container_name: mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: slurm_acct_db
      MYSQL_USER: slurm
      MYSQL_PASSWORD: password
    volumes:
      - var_lib_mysql:/var/lib/mysql
    networks:
      - slurm-network

  slurmdbd:
    image: slurm-docker-management:${IMAGE_TAG}
    build:
      context: components/slurm/.
      args:
        SLURM_TAG: ${SLURM_TAG}
    command: ["slurmdbd"]
    container_name: slurmdbd
    hostname: slurmdbd
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - var_log_slurm:/var/log/slurm
    expose:
      - "6819"
    depends_on:
      - "db_insaflu"
    networks:
      - slurm-network

  slurmctld:
    image: slurm-docker-management:${IMAGE_TAG}
    build:
      context: components/slurm/.
      args:
        SLURM_TAG: ${SLURM_TAG}
    command: ["slurmctld"]
    container_name: slurmctld
    hostname: slurmctld
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
    expose:
      - "6817"
    depends_on:
      - "slurmdbd"
      - "mysql"
    networks:
      - slurm-network

  c1:
    image: slurm-docker-nodes:${IMAGE_TAG}
    build:
      context: components/slurm_nodes/.
      args:
        SLURM_TAG: ${SLURM_TAG}
    command: ["slurmd"]
    hostname: c1
    container_name: c1
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
      - insaflu-website:/insaflu_web/INSaFLU
      - insaflu-software:/software
      - televir:/televir/mngs_benchmark

    expose:
      - "6818"
    depends_on:
      - "slurmctld"
    networks:
      - slurm-network

  c2:
    image: slurm-docker-nodes:${IMAGE_TAG}
    build:
      context: components/slurm_nodes/.
      args:
        SLURM_TAG: ${SLURM_TAG}
    command: ["slurmd"]
    hostname: c2
    container_name: c2
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
      - insaflu-website:/insaflu_web/INSaFLU  
      - insaflu-software:/software
      - televir:/televir/mngs_benchmark

    expose:
      - "6818"
    depends_on:
      - "slurmctld"
    networks:
      - slurm-network