exclude: "config/exclude_accessions_mpxv.txt"
reference: "config/reference.fasta"
genemap: "config/genemap.gff"
genbank_reference: "config/reference.gb"
colors: "config/colors_hmpxv1.tsv"
clades: "config/clades.tsv"
lat_longs: "config/lat_longs.tsv"
auspice_config: "config/auspice_config_hmpxv1_big.json"
description: "config/description.md"
tree_mask: "config/tree_mask.tsv"

strain_id_field: "accession"
#display_strain_field: "strain_original"
display_strain_field: "accession"

build_name: "hmpxv1_big"
auspice_name: "monkeypox_hmpxv1_big"

## filter
min_date: 2017
min_length: 10000
sequences_per_group: 1000
group_by: "year month country"
filters: "--exclude-where outbreak!=hMPXV-1"

## align
max_indel: 10000
seed_spacing: 1000

## treefix
fix_tree: true

## refine
timetree: true
root: "MK783032 MK783030"
clock_rate: 5.7e-5
clock_std_dev: 2e-5

## recency
recency: true

mask:
  from_beginning: 800
  from_end: 6422
  maskfile: "config/mask.bed"
