exclude: "config/exclude_accessions_mpxv.txt"
reference: "config/reference.fasta"
genemap: "config/genemap.gff"
genbank_reference: "config/reference.gb"
colors: "config/colors_mpxv.tsv"
lat_longs: "config/lat_longs.tsv"
auspice_config: "config/auspice_config_mpxv.json"
description: "config/description.md"
clades: "config/clades.tsv"
tree_mask: "config/tree_mask.tsv"

strain_id_field: "accession"
display_strain_field: "strain_original"

build_name: "mpxv"
auspice_name: "monkeypox_mpxv"

## filter
min_date: 1950
min_length: 10000
group_by: "clade year country"
sequences_per_group: 50

## align
max_indel: 10000
seed_spacing: 1000

## treefix
fix_tree: true

## refine
timetree: false
root: "min_dev"
clock_rate: 3e-6
clock_std_dev: 6e-6

## recency
recency: true

mask:
  from_beginning: 1350
  from_end: 6422
  maskfile: "config/mask_overview.bed"
