#!/bin/bash
set -e

echo "---> Updating Pathogen_identifcation ..."
cd /insaflu_web/INSaFLU;
python3 manage.py register_references_on_file -o /tmp/insaFlu/register --user_id 1
python3 manage.py register_references_on_file -o /tmp/insaFlu/register --user_id 1 --curate

echo "---> Done.  ..."
