#!/bin/bash
set -e -o pipefail

if [ $# -ne 2 ]
then
       echo "Need to pass an account to update the password."
       echo "use: update-password <account name>"
       echo ""
       echo "If you don't remenber your account do this command:"
       echo "$ list-all-users"
       exit 1
fi

## change account
echo "---> Change password for the account '$1'..."
python3 manage.py changepassword $1
