#!/bin/bash
set -e -o pipefail

echo "---> Stop apache server  ..."
service apache2 stop

## change account
echo "---> Update insaflu"
cd /insaflu_web/INSaFLU;

echo "---> git pull"
git pull;

echo "---> install requirements"
pip3 install -r requirements.txt

echo "---> collect some files"
python3 manage.py collectstatic --noinput

echo "---> migrate database"
python3 manage.py migrate

echo "---> reload defautl files"
python3 manage.py load_default_files;
python3 manage.py load_default_settings;

echo "---> Restart apache server  ..."
service apache2 start

echo "---> Everyhting was done"
