name: Rebuild all

on:
  workflow_dispatch:

jobs:
  rebuild_all:
    runs-on: ubuntu-latest
    env:
      GITHUB_RUN_ID: ${{ github.run_id }}
      SLACK_CHANNELS: monkeypox-updates
      SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT_GITHUB_DISPATCH }}
          event-type: rebuild
