
builds:
  current:
    title: "SARS-CoV-2 Nextstrain INSaFLU custom build"

configfile:
  - defaults/parameters.yaml # Pull in the default values

inputs:
  - name: current
    metadata: data/metadata.tsv
    sequences: data/sequences.fasta

refine:
    root: "Wuhan/Hu-1/2019"

files:
    include: data/include.txt
